from Board import Board
from Pawn import Pawn
#Fazer movimento de captura do peão e o inicio de pular duas casas
x=Board()
x.initialize_board()
print(x.actual_board)
y=Pawn(6,(1,"C"),"White",x)
w=Pawn(7,(6,"G"), "Black",x)
r=Pawn(8,(5,"G"),"Black",x)
t=Pawn(9,(2,"D"),"Black",x)
o=Pawn(10,(5,"F"),"Black",x)
p=Pawn(10,(5,"H"),"White",x)
x.update_piece(o)
x.update_piece(p)
x.update_piece(r)
x.update_piece(w)
x.update_piece(t)
x.print_board()
x.update_piece(y)
x.print_board()
y.find_capture()
y.move()
x.update_piece(y)
x.print_board()
y.move()
x.update_piece(y)
x.print_board()
y.move()
x.update_piece(y)
x.print_board()
y.find_capture()
y.move()
x.update_piece(y)
x.print_board()
y.move()
x.update_piece(y)
w.move()
x.update_piece(w)
x.print_board()
y.move()
x.update_piece(y)
x.print_board()
y.move()
x.update_piece(y)
x.print_board()
print(y.position[0])
y.move()
r.move()
x.update_piece(r)
x.print_board()
r.move()
x.update_piece(r)
x.print_board()
r.move()
x.update_piece(r)
x.print_board()
r.move()
x.update_piece(r)
x.print_board()
r.move()
x.update_piece(r)
x.print_board()
w.find_capture()



