from Board import Board
from Pawn import Pawn
from Knight import Knight
x=Board()
x.initialize_board()
y=Knight(1,(5,"E"),"White",x)
k=Knight(2,(8,"H"),"White",x)
f=Knight(3,(6,"G"),"Black",x)
t=Pawn(1,(2,"G"),"Black",x)
p=Pawn(2,(1,"H"),"Black",x)
x.update_piece(p)
x.update_piece(t)
x.update_piece(y)
x.update_piece(f)
x.update_piece(k)
x.print_board()
y.find_moves()
k.move((6,"G"))
x.update_piece(k)
x.print_board()
k.move((4,"H"))
x.update_piece(k)
x.print_board()
k.move((2,"G"))
x.update_piece(k)
x.print_board()
p.move((2,"G"))
x.update_piece(p)
x.print_board()
p.move_normal()
x.update_piece(p)
x.print_board()
print(x.pieces)